### ISSUE TITLE
YAML config stringifies numbers 

### ISSUE THREAD

**Issue by fila90** [Unibeautify/assistant#154]
When you try to export `.yaml` config number values are quoted

``` yaml
JavaScript:
  beautifiers:
    - Prettier
    - Pretty Diff
    - JS-Beautify
    - ESLint
  indent_size: '2'
  max_preserve_newlines: '1'
```

If I have numbers like that in my default config, plugin doesn't work.
When I remove quotes it works. 
Apparently you're expecting a number there and assistant outputs a string.
